package com.example.ps5controller;

import com.example.ps5controller.mixin.KeyBindingAccessor;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents;
import net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback;
import net.fabricmc.fabric.api.client.rendering.v1.WorldRenderEvents;
import net.fabricmc.fabric.api.client.screen.v1.ScreenEvents;
import net.fabricmc.fabric.api.client.screen.v1.Screens;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.Element;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.client.gui.screen.option.OptionsScreen;
import net.minecraft.client.gui.screen.ingame.HandledScreen;
import net.minecraft.client.gui.widget.ButtonWidget;
import net.minecraft.client.gui.widget.ClickableWidget;
import net.minecraft.client.option.KeyBinding;
import net.minecraft.client.util.math.MatrixStack;
import net.minecraft.screen.slot.Slot;
import net.minecraft.screen.slot.SlotActionType;
import net.minecraft.text.LiteralText;
import org.lwjgl.glfw.GLFW;
import org.lwjgl.glfw.GLFWGamepadState;
import org.lwjgl.system.MemoryStack;
import java.nio.ByteBuffer;
import java.nio.FloatBuffer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

public class PS5ControllerClient implements ClientModInitializer {
    public static class Pad { public volatile boolean active, jump, sneak; public volatile float forward, sideways; }
    public static final Pad PAD = new Pad();
    public static final String[] ACT = {"Jump","Sneak","Attack","Use","Inventory","Swap","Drop","Look","Hotbar next","Hotbar prev","Sprint","Pause"};
    public static final int[] BINDS = new int[ACT.length];
    public static volatile int listening = -1, mapping = 0;
    public static String padName = "None", layout = "PS5", battery = "Unknown";
    public static boolean connected;
    public static int selected = -1;
    public static float deadzone = 0.18f, lookSpeed = 1500f, menuSpeed = 1000f;
    public static boolean invertY, showGuide = true, guideFull = true, showStatus = true;
    public static int mapUp = 11, mapDown = 13, mapLeft = 14, mapRight = 12;
    public static void applyDefault() { layout = "PS5"; copy(new int[]{0,9,20,21,3,2,1,6,5,4,10,7}); save(); }
    public static void applyXbox() { layout = "Xbox"; copy(new int[]{0,9,21,20,3,2,1,6,5,4,10,7}); save(); }
    public static void applyLegion() { layout = "Legion Go"; copy(new int[]{0,9,21,20,3,2,1,6,5,4,10,7}); save(); }
    public static void applyPs3() { applyDefault(); }
    private static void copy(int[] d) { System.arraycopy(d,0,BINDS,0,BINDS.length); mapUp=11; mapDown=13; mapLeft=14; mapRight=12; }
    public static void usePad(int id) { selected = id; String n = GLFW.glfwGetJoystickName(id); String k = kind(n); if ("Xbox".equals(k)) applyXbox(); else if ("Legion Go".equals(k)) applyLegion(); else applyDefault(); }
    public static void cycleDeadzone(){ deadzone = deadzone>=0.3f?0.1f:Math.round((deadzone+0.04f)*100f)/100f; save(); }
    public static void cycleLook(){ lookSpeed = lookSpeed>=2200?800:lookSpeed+200; save(); }
    public static void cycleMenu(){ menuSpeed = menuSpeed>=1600?600:menuSpeed+200; save(); }
    public static void toggleInvert(){ invertY=!invertY; save(); }
    public static void toggleGuide(){ showGuide=!showGuide; save(); }
    public static void toggleGuideSize(){ guideFull=!guideFull; save(); }
    public static void toggleStatus(){ showStatus=!showStatus; save(); }
    public static void saveMap() { save(); }
    public static void setBind(int a, int b) { if (a>=0 && a<BINDS.length && b<11) BINDS[a]=b; save(); }
    public static String buttonName(int b) { boolean xbox = !"PS5".equals(layout); switch (b) { case 0: return xbox ? "A" : "Cross"; case 1: return xbox ? "B" : "Circle"; case 2: return xbox ? "X" : "Square"; case 3: return xbox ? "Y" : "Triangle"; case 4: return xbox ? "LB" : "L1"; case 5: return xbox ? "RB" : "R1"; case 6: return xbox ? "View" : "Create"; case 7: return xbox ? "Menu" : "Options"; case 9: return "LS"; case 10: return "RS"; case 20: return xbox ? "LT" : "L2"; case 21: return xbox ? "RT" : "R2"; default: return "Button "+b; } }
    public static int edgeButton() { if (l2() && !prevL2) return 20; if (r2() && !prevR2) return 21; for (int i = 0; i < 11; i++) if (bt[i] && !prev[i]) return i; return -1; }
    public static int dpadEdge() { int d = dpad(); return d==0 ? -1 : d; }
    private static final int CROSS=0,CIRCLE=1,SQUARE=2,TRIANGLE=3,L1=4,R1=5,OPTIONS=7,L3=9,R3=10;
    private static GLFWGamepadState state; private static final float[] ax = new float[6]; private static final boolean[] bt = new boolean[15], prev = new boolean[15];
    private static boolean sprint, mapped, leftHeld, prevL2, prevR2; private static int jid=-1, focus=-1, slotPick=-1, lastHat, prevHat; private static float restL=9f, restR=9f; private static long lastLook, lastMenu, lastNav, noDropUntil;
    private static final String SDL = "030000004c050000e60c000000000000,PS5 Controller,a:b1,b:b2,x:b0,y:b3,back:b8,start:b9,leftstick:b10,rightstick:b11,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpright:h0.2,dpdown:h0.4,dpleft:h0.8,lefttrigger:a3,righttrigger:a4,leftx:a0,lefty:a1,rightx:a2,righty:a5,platform:Windows,\n";
    @Override public void onInitializeClient() { load(); ClientTickEvents.START_CLIENT_TICK.register(PS5ControllerClient::tick); WorldRenderEvents.START.register(ctx -> look(MinecraftClient.getInstance())); HudRenderCallback.EVENT.register((m,d) -> hud(m)); ScreenEvents.AFTER_INIT.register((client, screen, w, h) -> { focus=-1; slotPick=-1; if (screen instanceof OptionsScreen) Screens.getButtons(screen).add(new ButtonWidget(screen.width / 2 + 5, screen.height - 28, 150, 20, new LiteralText("Controller"), b -> client.setScreen(new ControllerScreen(screen)))); ScreenEvents.afterRender(screen).register((s, matrices, mx, my, dt) -> menu(MinecraftClient.getInstance(), s, matrices)); }); }
    private static void tick(MinecraftClient mc) { boolean found = read(); connected = found; PAD.active = found && mc.player != null && mc.currentScreen == null; if (!PAD.active) { if (listening < 0 && mapping == 0) copyPrev(); return; } float lx=dz(ax[0]), ly=dz(ax[1]), mag=(float)Math.hypot(lx,ly); if (mag>0) { float out=Math.min(1f,mag/0.85f); PAD.forward=-(ly/mag)*out; PAD.sideways=-(lx/mag)*out; } else PAD.forward=PAD.sideways=0; PAD.jump = held(BINDS[0]); PAD.sneak = held(BINDS[1]); key(mc.options.keySneak, held(BINDS[1]), heldPrev(BINDS[1])); key(mc.options.keyAttack, held(BINDS[2]), heldPrev(BINDS[2])); key(mc.options.keyUse, held(BINDS[3]), heldPrev(BINDS[3])); edge(mc.options.keyInventory, BINDS[4]); edge(mc.options.keySwapHands, BINDS[5]); if (System.currentTimeMillis()>noDropUntil) edge(mc.options.keyDrop, BINDS[6]); if (BINDS[7] != BINDS[10]) edge(mc.options.keyTogglePerspective, BINDS[7]); if (edge(BINDS[8])) mc.player.getInventory().selectedSlot=(mc.player.getInventory().selectedSlot+1)%9; if (edge(BINDS[9])) mc.player.getInventory().selectedSlot=(mc.player.getInventory().selectedSlot+8)%9; if (edge(BINDS[10]) && BINDS[10] != BINDS[1]) sprint=!sprint; if (PAD.forward<=0.1f) sprint=false; mc.options.keySprint.setPressed(sprint); if (edge(BINDS[11])) mc.openPauseMenu(false); copyPrev(); }
    private static void look(MinecraftClient mc) { long n=System.nanoTime(); float dt=lastLook==0?0:Math.min(0.1f,(n-lastLook)/1_000_000_000f); lastLook=n; if (mc.player==null || mc.currentScreen!=null || !read()) return; float rx=dz(ax[2]), ry=dz(ax[3]); if (invertY) ry=-ry; if (rx!=0 || ry!=0) mc.player.changeLookDirection(rx*lookSpeed*dt, ry*lookSpeed*dt); }
    private static void hud(MatrixStack m) { if (!showStatus) return; MinecraftClient mc=MinecraftClient.getInstance(); if (mc.player==null || mc.currentScreen!=null) return; drawStatus(mc, m); }
    private static void drawStatus(MinecraftClient mc, MatrixStack m) { String t = connected ? "Connected  " + layout + "  " + padName + "  Battery: " + battery : "Not connected"; mc.textRenderer.drawWithShadow(m, t, 4, 4, connected ? 0x55FF55 : 0xFF5555); }
    public static java.util.List<String> pads() { java.util.List<String> out=new java.util.ArrayList<>(); for (int id=0; id<=GLFW.GLFW_JOYSTICK_LAST; id++) { if (!GLFW.glfwJoystickPresent(id)) continue; String n=GLFW.glfwGetJoystickName(id); out.add(id+": "+(n==null?"Controller":n)+(id==selected?"  [using]":"")); } return out; }
    private static void menu(MinecraftClient mc, Screen screen, MatrixStack matrices) { if (listening >= 0 || mapping > 0) return; if (mc.currentScreen!=screen || !read()) { if (showStatus && mc.currentScreen==screen) drawStatus(mc, matrices); return; } if (showStatus) drawStatus(mc, matrices); long handle=mc.getWindow().getHandle(); double[] cx={0}, cy={0}; GLFW.glfwGetCursorPos(handle,cx,cy); long n=System.nanoTime(); float dt=lastMenu==0?0:Math.min(0.1f,(n-lastMenu)/1_000_000_000f); lastMenu=n; int dir=dpad(); if (dir==0) { float mx=dz(ax[0]), my=dz(ax[1]); if (mx!=0 || my!=0) { int[] ww={1}, wh={1}; GLFW.glfwGetWindowSize(handle,ww,wh); cx[0]=clamp(cx[0]+mx*menuSpeed*dt,0,ww[0]-1); cy[0]=clamp(cy[0]+my*menuSpeed*dt,0,wh[0]-1); GLFW.glfwSetCursorPos(handle,cx[0],cy[0]); } } if (dir!=0 && System.currentTimeMillis()-lastNav>160) { if (screen instanceof HandledScreen) moveSlot(mc,(HandledScreen<?>)screen,dir); else moveButton(mc,screen,dir); lastNav=System.currentTimeMillis(); } double sx=cx[0]*screen.width/Math.max(1,mc.getWindow().getWidth()), sy=cy[0]*screen.height/Math.max(1,mc.getWindow().getHeight()); if (screen instanceof HandledScreen) highlightSlot(matrices, (HandledScreen<?>)screen); else highlightButton(matrices, screen); if (bt[CROSS] && !prev[CROSS]) { if (list(screen)) screen.keyPressed(GLFW.GLFW_KEY_ENTER,0,0); screen.mouseClicked(sx,sy,0); leftHeld=true; } if (!bt[CROSS] && prev[CROSS] && leftHeld) { screen.mouseReleased(sx,sy,0); leftHeld=false; } if (screen instanceof HandledScreen && held(BINDS[4]) && !heldPrev(BINDS[4])) quick(mc,(HandledScreen<?>)screen,sx,sy); if (bt[CIRCLE] && !prev[CIRCLE]) { screen.keyPressed(GLFW.GLFW_KEY_ESCAPE,0,0); noDropUntil=System.currentTimeMillis()+500; } CursorDraw.plus(matrices, sx, sy); copyPrev(); }
    private static int dpad() { boolean up = bt[11] || lastHat==1; boolean right = bt[12] || lastHat==2; boolean down = bt[13] || lastHat==4; boolean left = bt[14] || lastHat==8; if (left && !right) return 3; if (right && !left) return 4; if (up && !down) return 1; if (down && !up) return 2; return 0; }
    private static void highlightSlot(MatrixStack m, HandledScreen<?> screen) { Slot slot = byId(screen, slotPick); if (slot==null) return; int left=(screen.width-176)/2, top=top(screen); CursorDraw.box(m, left+slot.x, top+slot.y, 16, 16); }
    private static void highlightButton(MatrixStack m, Screen screen) { List<ClickableWidget> list = widgets(screen); if (focus<0 || focus>=list.size()) return; ClickableWidget w = list.get(focus); CursorDraw.box(m, w.x, w.y, w.getWidth(), w.getHeight()); }
    private static void moveButton(MinecraftClient mc, Screen screen, int dir) { List<ClickableWidget> list = widgets(screen); if (list.isEmpty()) return; if (focus<0 || focus>=list.size()) focus = 0; ClickableWidget cur = list.get(focus); double ox = cur.x + cur.getWidth()/2.0, oy = cur.y + cur.getHeight()/2.0, best = 1e9; int pick = focus; for (int i=0;i<list.size();i++) { if (i==focus) continue; ClickableWidget w = list.get(i); double dx = w.x + w.getWidth()/2.0 - ox, dy = w.y + w.getHeight()/2.0 - oy; boolean ok = dir==1 ? dy<-6 && Math.abs(dx)<=Math.abs(dy)+40 : dir==2 ? dy>6 && Math.abs(dx)<=Math.abs(dy)+40 : dir==3 ? dx<-6 && Math.abs(dy)<=Math.abs(dx)+20 : dx>6 && Math.abs(dy)<=Math.abs(dx)+20; if (!ok) continue; double score = dir<3 ? Math.abs(dy) : Math.abs(dx); if (score<best) { best=score; pick=i; } } focus = pick; ClickableWidget w = list.get(focus); GLFW.glfwSetCursorPos(mc.getWindow().getHandle(), (w.x+w.getWidth()/2.0)*mc.getWindow().getWidth()/screen.width, (w.y+w.getHeight()/2.0)*mc.getWindow().getHeight()/screen.height); }
    private static void moveSlot(MinecraftClient mc, HandledScreen<?> screen, int dir) { int left=(screen.width-176)/2, top=top(screen); Slot cur = byId(screen, slotPick); if (cur==null) { for (Slot s: screen.getScreenHandler().slots) { cur=s; break; } } if (cur==null) return; Slot pick=null; int best=100000; for (Slot slot: screen.getScreenHandler().slots) { if (slot==cur) continue; int dx=slot.x-cur.x, dy=slot.y-cur.y; boolean ok = dir==3 ? dx<0 && slot.y==cur.y : dir==4 ? dx>0 && slot.y==cur.y : dir==1 ? dy<0 && Math.abs(dx)<=8 : dy>0 && Math.abs(dx)<=8; if (!ok) continue; int score = dir==3 || dir==4 ? Math.abs(dx) : Math.abs(dy); if (score<best) { best=score; pick=slot; } } if (pick==null) return; slotPick = pick.id; GLFW.glfwSetCursorPos(mc.getWindow().getHandle(), (left+pick.x+8)*mc.getWindow().getWidth()/screen.width, (top+pick.y+8)*mc.getWindow().getHeight()/screen.height); }
    private static Slot byId(HandledScreen<?> screen, int id) { if (id<0) return null; for (Slot s: screen.getScreenHandler().slots) if (s.id==id) return s; return null; }
    private static List<ClickableWidget> widgets(Screen screen) { List<ClickableWidget> list=new ArrayList<>(); for (Element e: screen.children()) if (e instanceof ClickableWidget && ((ClickableWidget)e).visible) list.add((ClickableWidget)e); return list; }
    private static void quick(MinecraftClient mc, HandledScreen<?> screen, double sx, double sy) { Slot slot=byId(screen, slotPick); if (slot!=null && mc.player!=null && mc.interactionManager!=null) mc.interactionManager.clickSlot(screen.getScreenHandler().syncId, slot.id, 0, SlotActionType.QUICK_MOVE, mc.player); }
    private static int top(HandledScreen<?> screen) { int max=0; for (Slot s: screen.getScreenHandler().slots) if (s.y>max) max=s.y; return (screen.height-(max+26))/2; }
    private static boolean list(Screen screen) { for (Element e: screen.children()) if (e.getClass().getName().contains("WorldList")||e.getClass().getName().contains("EntryList")) return true; return false; }
    private static int prefer() { int any=-1, ps=-1; for (int id=0; id<=GLFW.GLFW_JOYSTICK_LAST; id++) { if (!GLFW.glfwJoystickPresent(id)) continue; if (any<0) any=id; if ("PS5".equals(kind(GLFW.glfwGetJoystickName(id)))) ps=id; } return ps>=0?ps:any; }
    private static String kind(String n) { String s=n==null?"":n.toLowerCase(); if (s.contains("legion")) return "Legion Go"; if (s.contains("xbox")||s.contains("xinput")||s.contains("360")||s.contains("microsoft")) return "Xbox"; return "PS5"; }
    private static boolean read() { if (state==null) state=GLFWGamepadState.malloc(); if (!mapped) { mapped=true; try (MemoryStack st=MemoryStack.stackPush()) { GLFW.glfwUpdateGamepadMappings(st.UTF8(SDL)); } catch (Throwable ignored) {} } if (selected<0 || !GLFW.glfwJoystickPresent(selected)) selected = prefer(); if (selected<0) { connected=false; battery="Unknown"; padName="None"; return false; } int id=selected; if (GLFW.glfwJoystickIsGamepad(id) && GLFW.glfwGetGamepadState(id, state)) { for (int i=0;i<6;i++) ax[i]=state.axes(i); for (int i=0;i<15;i++) bt[i]=state.buttons(i)==GLFW.GLFW_PRESS; } else { FloatBuffer a=GLFW.glfwGetJoystickAxes(id); ByteBuffer b=GLFW.glfwGetJoystickButtons(id); if (a==null||b==null||a.remaining()<4||b.remaining()<12) return false; ax[0]=a.get(0); ax[1]=a.get(1); ax[2]=a.remaining()>2?a.get(2):0; ax[3]=a.remaining()>5?a.get(5):0; ax[4]=a.remaining()>3?a.get(3):-1; ax[5]=a.remaining()>4?a.get(4):-1; for (int i=0;i<15;i++) bt[i]=false; bt[CROSS]=b.get(1)!=0; bt[CIRCLE]=b.get(2)!=0; bt[SQUARE]=b.get(0)!=0; bt[TRIANGLE]=b.get(3)!=0; bt[L1]=b.get(4)!=0; bt[R1]=b.get(5)!=0; bt[OPTIONS]=b.remaining()>9 && b.get(9)!=0; if (b.remaining()>10) bt[L3]=b.get(10)!=0; if (b.remaining()>11) bt[R3]=b.get(11)!=0; } hats(id); jid=id; String n=GLFW.glfwGetJoystickName(id); padName=n==null?"Controller":n; battery = batteryOf(id); if (restL>2f) { restL=ax[4]; restR=ax[5]; } return true; }
    private static String batteryOf(int id) { try { java.lang.reflect.Method m = GLFW.class.getMethod("glfwGetJoystickBatteryLevel", int.class); int v = (Integer) m.invoke(null, id); switch (v) { case 0: return "Empty"; case 1: return "Low"; case 2: return "Medium"; case 3: return "Full"; case 4: return "Wired"; default: return "Unknown"; } } catch (Throwable t) { return "Unknown"; } }
    private static void hats(int id) { lastHat=0; try { ByteBuffer h=GLFW.glfwGetJoystickHats(id); if (h==null) return; for (int i=0;i<h.remaining();i++) { int hat=h.get(i)&0xFF; if (hat!=0) lastHat=hat; if (hat==1) bt[11]=true; if (hat==2) bt[12]=true; if (hat==4) bt[13]=true; if (hat==8) bt[14]=true; } } catch (Throwable ignored) {} }
    private static boolean l2(){return ax[4]-restL>0.4f;} private static boolean r2(){return ax[5]-restR>0.4f;} private static boolean held(int b){return b==20?l2():b==21?r2():b>=0&&b<bt.length&&bt[b];} private static boolean heldPrev(int b){return b==20?prevL2:b==21?prevR2:b>=0&&b<prev.length&&prev[b];} private static boolean edge(int b){return held(b)&&!heldPrev(b);} private static void edge(KeyBinding kb,int b){key(kb,held(b),heldPrev(b));} private static void key(KeyBinding kb, boolean down, boolean was) { if (down && !was) { KeyBindingAccessor a=(KeyBindingAccessor)kb; a.ps5$setTimesPressed(a.ps5$getTimesPressed()+1); } if (down!=was) kb.setPressed(down); } private static void copyPrev(){ System.arraycopy(bt,0,prev,0,15); prevL2=l2(); prevR2=r2(); prevHat=lastHat; } private static double clamp(double v,double a,double b){return Math.max(a,Math.min(b,v));} private static float dz(float v){float a=Math.abs(v); return a<deadzone?0:Math.copySign((a-deadzone)/(1-deadzone),v);} private static Path file(){return FabricLoader.getInstance().getConfigDir().resolve("ps5binds3.txt");}
    private static void load(){ applyDefault(); try { if (!Files.exists(file())) return; String raw=Files.readString(file()).trim(); int hash=raw.lastIndexOf('#'); if (hash>=0) { String[] flags=raw.substring(hash+1).split(","); if (flags.length>=4) { showGuide=Boolean.parseBoolean(flags[0]); showStatus=Boolean.parseBoolean(flags[1]); invertY=Boolean.parseBoolean(flags[2]); guideFull=Boolean.parseBoolean(flags[3]); } } } catch (Exception ignored) {} applyDefault(); }
    private static void save(){ try { StringBuilder sb=new StringBuilder(); for (int i=0;i<BINDS.length;i++){ if(i>0)sb.append(','); sb.append(BINDS[i]); } sb.append('|').append(mapUp).append(',').append(mapDown).append(',').append(mapLeft).append(',').append(mapRight); sb.append('#').append(showGuide).append(',').append(showStatus).append(',').append(invertY).append(',').append(guideFull); Files.writeString(file(), sb.toString()); } catch (Exception ignored) {} }
}
